name: Stop Railway (19:00 BRT)

on:
  schedule:
    - cron: "0 22 * * *"   # GitHub Actions usa UTC → 22:00 UTC = 19:00 BRT
  workflow_dispatch: {}     # permite rodar manualmente

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH
      - name: Login
        run: railway login --token "${{ secrets.RAILWAY_TOKEN }}"
      - name: Link project
        run: railway link --project "${{ secrets.RAILWAY_PROJECT_ID }}"
      - name: Stop project services
        run: railway down
