name: Start Railway (07:00 BRT)

on:
  schedule:
    - cron: "0 10 * * *"   # 10:00 UTC = 07:00 BRT
  workflow_dispatch: {}

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH
      - name: Login
        run: railway login --token "${{ secrets.RAILWAY_TOKEN }}"
      - name: Link project
        run: railway link --project "${{ secrets.RAILWAY_PROJECT_ID }}"
      # Opção 1: religar TUDO (projeto inteiro)
      - name: Redeploy project
        run: railway redeploy
      # Opção 2: religar só 1 serviço (descomente se quiser)
      # - name: Redeploy one service
      #   run: railway redeploy --service "${{ secrets.RAILWAY_SERVICE }}"
